<?php
$english = [
    //adm_settings.php
    'langSettingsPageTitle' => 'Settings',
    'langPageTitleSetting' => 'Page Title:',
    'langPageTitleHelp' => 'This is the title of the page displayed in the browser\'s title bar and in the navigation bar heading.',
    'langQuizName' => 'Quiz Name:',
    'langQuizNameHelp' => 'This is the name of the quiz displayed on the quiz page.',
    'langUserGreeting' => 'User greeting:',
    'langUserGreetingHelp' => 'This greeting message will be displayed in the user info pop-up.',
    'langSaveSettings' => 'Save Settings',
    'langLanguage' => 'Language:',
    'langEnglish' => 'English',
    'langNorwegian' => 'Norwegian',
    'langRegisteredUsers' => 'Registered users',
    'langFullName' => 'Full Name',
    'langUsername' => 'Username',
    'langAction' => 'Action',
    'langResetPassword' => 'Reset Password',
    'langDeleteUser' => 'Delete User',
    'langSuccess' => 'Success',
    'langPasswordReset' => 'Password reset successfully.',
    'langOK' => 'OK',
    'langWelcomeMessage' => 'Welcome message:',
    'langWelcomeMessageHelp' => 'This message will welcome the users on the quiz page. You can style the message using HTML tags like ' . htmlspecialchars('<b></b>, <i></i>') . ', etc.',
    'langFaviconURL' => 'Favicon URL:',
    'langFaviconURLHelp' => 'URL to include favicon. Example: ' . htmlspecialchars('<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎯</text></svg>') . '<br>You can generate links here: <a href="https://emojitofavicon.com/" title="emojitofavicon" target="_blank">https://emojitofavicon.com/</a>',
    'langMaintMode' => 'Maintenance mode:',
    'langMaintModOn' => 'On',
    'langMaintModeOff' => 'Off',
    'langMaintModeHelp' => 'Activates/deactivates maintenance mode.',
    'langMaintModeText' => 'Mainenance message:',
    'langMaintModeTextHelp' => 'The message that appears in the maintenance mode banner. Top - English, Bottom - Norwegian. You can style the message using HTML tags like ' . htmlspecialchars('<b></b>, <i></i>') . ', etc.',
    //quiz.php
    'langQuizPageTitle' => 'Quiz',
    'langQuizSubmit' => 'Submit',
    'langQuizSuccess' => 'Answers submitted successfully!',
    'langQuizQuestion' => 'Question',
    'langQuizPreviousAnswer' => 'Previous Answer',
    'langQuizEndDateMessage' => 'This question is available to',
    'langQuizPastEndDateMessage' => 'This question became unavailable after',
    'langQuizDateFormat' => 'F j, Y',
    'langWelcomeMessage' => '',
    // Navigation
    'langNavQuiz' => 'Back to Quiz',
    'langNavAddQuestion' => 'Question management',
    'langNavSubmissions' => 'Submissions',
    'langNavSettings' => 'Settings',
    'langNavSignOut' => 'Sign out',
    'langNavDefaultUserGreeting' => 'Welcome',
    'langNavGreeting' => 'Welcome',
    // Add Question page
    'langAddQuestionPageTitle' => 'Manage Quiz Questions',
    'langAddQuestionFormTitle' => 'Add Question',
    'langAddQuestionFormLabel' => 'Question Text:',
    'langAddQuestionFormButton' => 'Add Question',
    'langEditQuestionFormTitle' => 'Edit Question',
    'langEditQuestionFormLabel' => 'Edit Question:',
    'langEditQuestionFormButton' => 'Edit',
    'langDeleteQuestionButton' => 'Delete',
    'langExistingQuestionsTitle' => 'Existing Questions',
    'langAddQuestionIntroLabel' => 'Question Introduction:',
    'langEditQuestionIntroLabel' => 'Edit question Introduction:',
    'langAddQuestionStartDateLabel' => 'Available from:',
    'langAddQuestionEndDateLabel' => 'Unavailable after:',
    'langQuestionActiveCheckboxLabel' => 'Activate question',
    // adm_submissions.php
    'langSubmissionsPageTitle' => 'Quiz Submissions',
    'langSubmissionsQuestionText' => 'Question',
    'langSubmissionsUser' => 'User',
    'langSubmissionsAnswer' => 'Answer',
    // Modals
    'langYouAreAdmin' => 'You are Admin',
    'langUserInfoTitle' => 'User information',
    'langUserInfoName' => 'Name:',
    'langUserInfoID' => 'User ID:',
    'langSuccess' => 'Success',
    'langQuizSuccess' => 'Answers submitted successfully!',
    'langEditQuestionFormLabel' => 'Edit question:',
    'langAddQuestionFormLabel' => 'Add a question:',
    'langDeleteQuestionButton' => 'Delete Question!',
    // Cookie text
    'langCookieText' => 'This website uses cookies to enhance your experience. We do not store any personally sensitive information or tracking statistics.',
    'langCookieButton' => 'I understand',
];

$norwegian = [
    // adm_settings.php
    'langSettingsPageTitle' => 'Innstillinger',
    'langPageTitleSetting' => 'Sidetittel:',
    'langPageTitleHelp' => 'Dette er tittelen på siden som vises i nettleserens tittellinje og i navigasjonsfeltets overskrift.',
    'langQuizName' => 'Quiznavn:',
    'langQuizNameHelp' => 'Dette er navnet på quizen som vises på quizens side.',
    'langUserGreeting' => 'Brukerhilsen:',
    'langUserGreetingHelp' => 'Denne hilsenen vil vises i brukerinfo pop-upen.',
    'langSaveSettings' => 'Lagre innstillinger',
    'langLanguage' => 'Språk:',
    'langEnglish' => 'Engelsk',
    'langNorwegian' => 'Norsk',
    'langRegisteredUsers' => 'Registrerte brukere',
    'langFullName' => 'Fullt navn',
    'langUsername' => 'Brukernavn',
    'langAction' => 'Handling',
    'langResetPassword' => 'Tilbakestill passord',
    'langDeleteUser' => 'Slett bruker',
    'langSuccess' => 'Suksess',
    'langPasswordReset' => 'Passordet er tilbakestilt.',
    'langOK' => 'OK',
    'langWelcomeMessage' => 'Velkomstmelding:',
    'langWelcomeMessageHelp' => 'Denne meldingen ønsker brukerne velkommen på quiz siden. Du kan formatere teksten med HTML som ' . htmlspecialchars('<b></b>, <i></i>') . ', etc.',
    'langFaviconURL' => 'Favicon URL:',
    'langFaviconURLHelp' => 'URL for å inkludere favicon. Eksempel: ' . htmlspecialchars('<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎯</text></svg>') . '<br>Du kan generere linker her: <a href="https://emojitofavicon.com/" title="emojitofavicon" target="_blank">https://emojitofavicon.com/</a>',
    'langMaintMode' => 'Vedlikeholdsmodus:',
    'langMaintModOn' => 'På',
    'langMaintModeOff' => 'Av',
    'langMaintModeHelp' => 'Slå på/av vedlikeholdsmodus.',
    'langMaintModeText' => 'Vedlikeholdsvarsel:',
    'langMaintModeTextHelp' => 'Meldingen som vises når vedlikeholdsmodus er slått på. Topp - Engelsk, Bunn - Norsk. Du kan formatere teksten med HTML som ' . htmlspecialchars('<b></b>, <i></i>') . ', etc.',
    // quiz.php
    'langQuizPageTitle' => 'Quiz',
    'langQuizSubmit' => 'Send inn',
    'langQuizSuccess' => 'Svarene ble sendt inn!',
    'langQuizQuestion' => 'Spørsmål',
    'langQuizPreviousAnswer' => 'Forrige svar',
    'langQuizEndDateMessage' => 'Dette spørsmålet er tilgjengelig til',
    'langQuizPastEndDateMessage' => 'Dette spørsmålet ble utilgjengelig etter',
    'langQuizDateFormat' => 'd/m, Y',
    'langWelcomeMessage' => '',
    // Navigation
    'langNavQuiz' => 'Tilbake til Quiz',
    'langNavAddQuestion' => 'Administrer spørsmål',
    'langNavSubmissions' => 'Innsendinger',
    'langNavSettings' => 'Innstillinger',
    'langNavSignOut' => 'Logg ut',
    'langNavDefaultUserGreeting' => 'Velkommen',
    'langNavGreeting' => 'Velkommen',
    // Add Question page
    'langAddQuestionPageTitle' => 'Administrer quizspørsmål',
    'langAddQuestionFormTitle' => 'Legg til spørsmål',
    'langAddQuestionFormLabel' => 'Spørsmål:',
    'langAddQuestionFormButton' => 'Legg til spørsmål',
    'langEditQuestionFormTitle' => 'Rediger spørsmål',
    'langEditQuestionFormLabel' => 'Rediger spørsmål:',
    'langEditQuestionFormButton' => 'Rediger',
    'langDeleteQuestionButton' => 'Slett',
    'langExistingQuestionsTitle' => 'Eksisterende spørsmål',
    'langAddQuestionIntroLabel' => 'Introduksjon til spørsmålet:',
    'langEditQuestionIntroLabel' => 'Rediger introduksjon til spørsmålet:',
    'langAddQuestionStartDateLabel' => 'Tilgjengelig fra:',
    'langAddQuestionEndDateLabel' => 'Utilgjengelig etter:',
    'langQuestionActiveCheckboxLabel' => 'Aktiver spørsmål',
    // adm_submissions.php
    'langSubmissionsPageTitle' => 'Quiz Innsendinger',
    'langSubmissionsQuestionText' => 'Spørsmål',
    'langSubmissionsUser' => 'Bruker',
    'langSubmissionsAnswer' => 'Svar',
    // Modals
    'langYouAreAdmin' => 'Du er Admin',
    'langUserInfoTitle' => 'Brukerinformasjon',
    'langUserInfoName' => 'Navn:',
    'langUserInfoID' => 'Bruker ID:',
    'langSuccess' => 'Suksess',
    'langQuizSuccess' => 'Svarene ble sendt inn!',
    'langEditQuestionFormLabel' => 'Rediger spørsmål:',
    'langAddQuestionFormLabel' => 'Lag et nytt spørsmål:',
    'langDeleteQuestionButton' => 'Slett spørsmål!',
    // Cookie text
    'langCookieText' => 'Dette nettstedet bruker informasjonskapsler for å forbedre opplevelsen din. Vi lagrer ikke noe personsensitiv informasjon eller sporingsstatistikk.',
    'langCookieButton' => 'Jeg forstår'
];
?>
